Auktioner/Controllers/AddCategoryController.cs
using Auktioner.Models;
using Auktioner.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Auktioner.Controllers
{
    [Authorize]
    public class AddCategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;

        public AddCategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        public IActionResult Add()
        {
            AddCategoryViewModel model = new();
            model.Categories = _categoryRepository.AllCategories;
            return View(model);
        }

        [HttpPost]
        public IActionResult Add(AddCategoryViewModel model)
        {
            model.Categories = _categoryRepository.AllCategories;
            var categoryExists = _categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == model.CategoryName);
            if(categoryExists != null)
            {
                ViewBag.CategoryNameExists = "Kategorin finns redan, testa en annan";
                return View(model);
            }

            if (ModelState.IsValid)
            {
                Category category = new()
                {
                    CategoryId = model.CategoryId,
                    CategoryName = model.CategoryName,
                };
                _categoryRepository.AddCategory(category);
                return RedirectToAction("CategoryAdded");
            }
            return View(model);
        }

        public IActionResult CategoryAdded()
        {
            ViewBag.CategoryAddedMessage = "Tack. Du har nu lagt till en kategori!";
            return View();
        }
    }
}

Auktioner/Controllers/AddItemController.cs
using Auktioner.Models;
using Auktioner.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Auktioner.Controllers
{
    [Authorize]
    public class AddItemController : Controller
    {
        private readonly IAuctionItemRepository _auctionItemRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly UserManager<AppUser> _userManager;

        public AddItemController(IAuctionItemRepository auctionItemRepository, ICategoryRepository categoryRepository, UserManager<AppUser> userManager)
        {
            _auctionItemRepository = auctionItemRepository;
            _categoryRepository = categoryRepository;
            _userManager = userManager;
        }
        public IActionResult Add()
        {
            AddItemViewModel model = new();
            model.Categories = _categoryRepository.AllCategories;
            return View(model);
        }
        [HttpPost]
        public IActionResult Add(AddItemViewModel model)
        {
            var auctionItemExists = _auctionItemRepository.AllAuctionItems.FirstOrDefault(i => i.AuctionItemId == model.AuctionItemId);
            model.Categories = _categoryRepository.AllCategories;
            if(auctionItemExists != null)
            { 
                ViewBag.IDExists = "ID upptaget, testa ett annat";
                return View(model);
            }

            if (ModelState.IsValid)
            {
                AuctionItem auctionItem = new()
                {
                    AuctionItemId = model.AuctionItemId,
                    Name = model.Name,
                    Description = model.Description,
                    Costs = model.Costs,
                    StartingPrice = model.StartingPrice,
                    Decade = model.Decade,
                    Purchaser = _userManager.GetUserName(User),
                    CategoryName = model.CategoryName
                };
                _auctionItemRepository.AddToInventory(auctionItem);
                return RedirectToAction("AuctionItemAdded");
            }
            return View(model);
        }

        public IActionResult AuctionItemAdded()
        {
            ViewBag.AuctionItemAddedMessage = "Tack. Du har nu lagt till objektet i inventarierna!";
            return View();
        }
    }
}

Auktioner/Controllers/InventoryController.cs
using Auktioner.Models;
using Auktioner.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Auktioner.Controllers
{
    [Authorize]
    public class InventoryController : Controller
    {
        private readonly IAuctionItemRepository _auctionItemRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly UserManager<AppUser> _userManager;

        public InventoryController(IAuctionItemRepository auctionItemRepository, ICategoryRepository categoryRepository, UserManager<AppUser> userManager)
        {
            _auctionItemRepository = auctionItemRepository;
            _categoryRepository = categoryRepository;
            _userManager = userManager;
        }

        public ViewResult List()
        {
            var user = _userManager.Users.FirstOrDefault(u => u.Id == _userManager.GetUserId(User));
            if(user.IsAuctioneer)
            {
                return View(new InventoryListViewModel
                {
                    AuctionItems = _auctionItemRepository.AuctionItemsInStock(),
                    ThisUser = user
                });;
            }
            else
            {
                return View(new InventoryListViewModel
                {
                    AuctionItems = _auctionItemRepository.SoldAuctionItems(user.UserName),
                    ThisUser = user
                });
            }
        }
        
        public IActionResult Edit(string itemId)
        {
            var auctionItem = _auctionItemRepository.GetAuctionItemById(itemId);
            if(auctionItem == null)
            {
                return NotFound();
            }
            return View(new EditItemViewModel
            {
                AuctionItemId = auctionItem.AuctionItemId,
                Name = auctionItem.Name,
                Description = auctionItem.Description,
                Costs = auctionItem.Costs,
                StartingPrice = auctionItem.StartingPrice,
                CategoryName = auctionItem.CategoryName,
                Categories = _categoryRepository.AllCategories,
                ThisUser = _userManager.Users.FirstOrDefault(u => u.Id == _userManager.GetUserId(User))
            });
        }

        [HttpPost]
        public IActionResult Edit(EditItemViewModel model)
        { 
            model.Categories = _categoryRepository.AllCategories;
            if (ModelState.IsValid)
            {
                AuctionItem auctionItem = _auctionItemRepository.GetAuctionItemById(model.AuctionItemId);
                auctionItem.Name = model.Name;
                auctionItem.Description = model.Description;
                auctionItem.StartingPrice = model.StartingPrice;
                auctionItem.Costs = model.Costs;
                auctionItem.CategoryName = model.CategoryName;

                _auctionItemRepository.Update(auctionItem);
                return RedirectToAction("AuctionItemUpdated");
            }
            return View(model);
        }

        public IActionResult AuctioneerEdit(string itemId)
        {
            var auctionItem = _auctionItemRepository.GetAuctionItemById(itemId);
            if (auctionItem == null)
            {
                return NotFound();
            }
            return View(new AuctioneerEditViewModel
            {
                AuctionItemId = auctionItem.AuctionItemId,
                Name = auctionItem.Name,
                Description = auctionItem.Description,
                Costs = auctionItem.Costs,
                StartingPrice = auctionItem.StartingPrice,
                FinalPrice = auctionItem.FinalPrice,
                Decade = auctionItem.Decade,
                Purchaser = auctionItem.Purchaser,
                InStock = auctionItem.InStock,
                CategoryName = auctionItem.CategoryName,
                ThisUser = _userManager.Users.FirstOrDefault(u => u.Id == _userManager.GetUserId(User))
            });
        }

        [HttpPost]
        public IActionResult AuctioneerEdit(AuctioneerEditViewModel model)
        {
            var user = _userManager.Users.FirstOrDefault(u => u.Id == _userManager.GetUserId(User));
            model.ThisUser = user; 
            
            if (user.IsAuctioneer)
            {
                if (ModelState.IsValid)
                {
                    AuctionItem auctionItem = _auctionItemRepository.GetAuctionItemById(model.AuctionItemId);
                    auctionItem.AuctionItemId = model.AuctionItemId;
                    auctionItem.FinalPrice = model.FinalPrice;
                    auctionItem.InStock = model.InStock;

                    _auctionItemRepository.Update(auctionItem);
                    return RedirectToAction("AuctionItemUpdated");
                }
                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        public IActionResult AuctionItemUpdated()
        {
            ViewBag.AuctionItemUpdatedMessage = "Tack. Du har nu uppdaterat objektet!";
            return View();
        }
    }
}

Auktioner/Views/Shared/_AuctionItemCard.cshtml
@model AuctionItem
<div>
    <h3>@Model.Name</h3>
    <p>ID: @Model.AuctionItemId</p>
    <p>Objektsbeskrivning: @Model.Description</p>
    <p>Objektskostnad: @Model.Costs.ToString("c")</p>
    <p>Utgångspris: @Model.StartingPrice.ToString("c")</p>
    <p>Slutpris: @Model.FinalPrice.ToString("c")</p>
    <p>Tillverkad årtionde: @Model.Decade</p> 
    <p>Inköpare: @Model.Purchaser</p>
    <p>Kategori: @Model.CategoryName</p>
    @if(Model.InStock)
    {
      <p>I lager: Ja</p>  
    } else
    {
      <p>I lager: Nej</p> 
    } 
</div>

Auktioner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Auktioner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Auktioner</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">     
                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Start</a></li>
                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="List">Inventarier</a></li> 
                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="OutOfStock" asp-action="List">Lämnat lagret</a></li>
                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="AddItem" asp-action="Add">Lägg till Objekt</a></li>
                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="AddCategory" asp-action="Add">Lägg till Kategori</a></li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Auktioner 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>